---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-debian-12"
  gather_facts: false
  tasks:

    - name: "Get Filebeat service current state"
      register: install_filebeat__service_status
      failed_when: not install_filebeat__service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "filebeat"

    - name: "Check Filebeat configuration file"
      register: file_stat
      failed_when: not file_stat.stat.exists
      ansible.builtin.stat:
        path: "{{ inv_install_filebeat__config_path }}/filebeat.yml"

    - name: "Check Filebeat configurations folder"
      register: file_stat
      failed_when: not file_stat.stat.exists
      ansible.builtin.stat:
        path: "{{ inv_install_filebeat__confs_path }}"
