---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_filebeat"
      tags:
        - "labocbz.install_filebeat"
      vars:
        install_filebeat_major_version: "{{ inv_install_filebeat_major_version }}"
        install_filebeat_config_path: "{{ inv_install_filebeat_config_path }}"
        install_filebeat_confs_path: "{{ inv_install_filebeat_confs_path }}"
        install_filebeat_ssl_authorities: "{{ inv_install_filebeat_ssl_authorities }}"
        install_filebeat_ssl_path: "{{ inv_install_filebeat_ssl_path }}"
        install_filebeat_logstash_ssl: "{{ inv_install_filebeat_logstash_ssl }}"
        install_filebeat_logstash_hosts: "{{ inv_install_filebeat_logstash_hosts }}"
        install_filebeat_logstash_client_auth: "{{ inv_install_filebeat_logstash_client_auth }}"
        install_filebeat_group: "{{ inv_install_filebeat_group }}"
        install_filebeat_ssl_crt: "{{ inv_install_filebeat_ssl_crt }}"
        install_filebeat_ssl_key: "{{ inv_install_filebeat_ssl_key }}"
        install_filebeat_confs_reload: "{{ inv_install_filebeat_confs_reload }}"
        install_filebeat_workers: "{{ inv_install_filebeat_workers }}"
        install_filebeat_loglevel: "{{ inv_install_filebeat_loglevel }}"
        install_filebeat_log_keeping: "{{ inv_install_filebeat_log_keeping }}"
      ansible.builtin.include_role:
        name: "labocbz.install_filebeat"
