---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_filebeat"
      tags:
        - "labocbz.install_filebeat"
      vars:
        install_filebeat__major_version: "{{ inv_install_filebeat__major_version }}"
        install_filebeat__config_path: "{{ inv_install_filebeat__config_path }}"
        install_filebeat__confs_path: "{{ inv_install_filebeat__confs_path }}"
        install_filebeat__ssl_authorities: "{{ inv_install_filebeat__ssl_authorities }}"
        install_filebeat__ssl_path: "{{ inv_install_filebeat__ssl_path }}"
        install_filebeat__logstash_ssl: "{{ inv_install_filebeat__logstash_ssl }}"
        install_filebeat__logstash_hosts: "{{ inv_install_filebeat__logstash_hosts }}"
        install_filebeat__logstash_client_auth: "{{ inv_install_filebeat__logstash_client_auth }}"
        install_filebeat__group: "{{ inv_install_filebeat__group }}"
        install_filebeat__ssl_crt: "{{ inv_install_filebeat__ssl_crt }}"
        install_filebeat__ssl_key: "{{ inv_install_filebeat__ssl_key }}"
        install_filebeat__confs_reload: "{{ inv_install_filebeat__confs_reload }}"
        install_filebeat__workers: "{{ inv_install_filebeat__workers }}"
        install_filebeat__loglevel: "{{ inv_install_filebeat__loglevel }}"
        install_filebeat__log_keeping: "{{ inv_install_filebeat__log_keeping }}"
      ansible.builtin.include_role:
        name: "labocbz.install_filebeat"
